### ISSUE TITLE
Documentation and/or more details

### ISSUE THREAD

**Issue by mohamnag** [albfernandez/itext2#3]
I just happened to find this library, after having some problems with Flying Saucer. What I could not find out easily is how this library can be used and wether or not this contains additional iText plugins like XMLWorker or not?

Could you provide these basic information to make it easier to make first steps in making the decision whether or not to use this lib?

**Comment by albfernandez** [comment]
The main goal of the project is to maintain the last LGPL version of iText.
Starting at iText 5 they switched to GNU Affero General Public License, wich is not suitable for a lot of projects, where LGPL fits better.
The main goal is to maintain compatibility with last JDK and BouncyCastle, some bug fixing (most of them taken from other forks) and some custom patches.

XMLWorker cannot be included because the licensing issue I pointed before.
